<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Spring Boot Parent -->

    <parent>

        <groupId>org.springframework.boot</groupId>

        <artifactId>spring-boot-starter-parent</artifactId>

        <version>2.7.18</version>

        <relativePath/>

    </parent>

    <!-- Project Info -->

    <groupId>com.mt</groupId>

    <artifactId>sunglasses-store</artifactId>

    <version>1.0</version>

    <packaging>war</packaging>

    <name>sunglasses-store</name>

    <description>Sunglasses Store WAR Application</description>

    <!-- Properties -->

    <properties>

        <java.version>11</java.version>

        <project.build.sourceEncoding>
            UTF-8
        </project.build.sourceEncoding>

        <project.reporting.outputEncoding>
            UTF-8
        </project.reporting.outputEncoding>

        <!-- SonarQube -->

        <sonar.host.url>
            http://13.206.89.11:9000/
        </sonar.host.url>

        <sonar.login>
            squ_44c9e31c2680b7b1b281fe534b3a09202964c6ce
        </sonar.login>

    </properties>

    <!-- Dependencies -->

    <dependencies>

        <!-- Spring Boot Web -->

        <dependency>

            <groupId>org.springframework.boot</groupId>

            <artifactId>spring-boot-starter-web</artifactId>

        </dependency>

        <!-- External Tomcat -->

        <dependency>

            <groupId>org.springframework.boot</groupId>

            <artifactId>spring-boot-starter-tomcat</artifactId>

            <scope>provided</scope>

        </dependency>

        <!-- Testing -->

        <dependency>

            <groupId>org.springframework.boot</groupId>

            <artifactId>spring-boot-starter-test</artifactId>

            <scope>test</scope>

        </dependency>

    </dependencies>

    <!-- Distribution Management -->

    <distributionManagement>

        <repository>

            <id>nexus</id>

            <name>Nexus Release Repository</name>

            <url>
                http://52.66.206.14:8081/repository/maven-releasenew/
            </url>

        </repository>

    </distributionManagement>

    <!-- Build -->

    <build>

        <!-- Custom Source Path -->

        <sourceDirectory>
            backend/src/main/java
        </sourceDirectory>

        <!-- Resource Path -->

        <resources>

            <resource>

                <directory>
                    backend/src/main/resources
                </directory>

            </resource>

        </resources>

        <!-- Final WAR Name -->

        <finalName>sunglasses-store</finalName>

        <!-- Plugins -->

        <plugins>

            <!-- Spring Boot Plugin -->

            <plugin>

                <groupId>org.springframework.boot</groupId>

                <artifactId>spring-boot-maven-plugin</artifactId>

            </plugin>

            <!-- Compiler Plugin -->

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>

                <artifactId>maven-compiler-plugin</artifactId>

                <version>3.11.0</version>

                <configuration>

                    <source>${java.version}</source>

                    <target>${java.version}</target>

                </configuration>

            </plugin>

            <!-- WAR Plugin -->

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>

                <artifactId>maven-war-plugin</artifactId>

                <version>3.4.0</version>

            </plugin>

            <!-- Sonar Plugin -->

            <plugin>

                <groupId>org.sonarsource.scanner.maven</groupId>

                <artifactId>sonar-maven-plugin</artifactId>

                <version>3.10.0.2594</version>

            </plugin>

        </plugins>

    </build>

</project>
